version: "3.8"

services:
  # ✅ Redis Stack server (includes RediSearch + RedisJSON modules)
  redis:
    image: redis/redis-stack-server:7.4.0-v6
    container_name: redis-stack
    restart: unless-stopped
    command: ["redis-stack-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - TZ=UTC

  # (optional) RedisInsight web UI at http://localhost:8001
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - TZ=UTC
    depends_on:
      - redis

volumes:
  redis-data:
